### Lecture 1: Solutions

<i>Whenever you are asked to 'create' an array, do this as efficiently as possible in terms of code, by using the functions described in the theory. Don't hardcode the solution!</i>

In [1]:
#Create a .py file in which you solve the exericses below. Don't forget to import the numpy module (e.g. as np)
import numpy as np

<b>1:</b>  Create an `3*2` integer array `x` of ones.

In [2]:
x = np.ones((3,2),dtype='int')
print(x)
#If you don't specify the dtype, then the vector will have dtype 'float64' (You can check this with the command: x.dtype)

[[1 1]
 [1 1]
 [1 1]]


<b>2:</b>  Create the numpy array ```x = [2, 4, 6, 8, ..., 100]```.

In [3]:
x = np.arange(2,102,2) 
print(x)
#np.arange(2,102,2) gives the same result.
#np.arange(2,100,2) does not give the same result as the upper bound of 100 is not included.

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


<b>3:</b>  Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [4]:
x = np.linspace(3,10,50)
print(x)

[ 3.          3.14285714  3.28571429  3.42857143  3.57142857  3.71428571
  3.85714286  4.          4.14285714  4.28571429  4.42857143  4.57142857
  4.71428571  4.85714286  5.          5.14285714  5.28571429  5.42857143
  5.57142857  5.71428571  5.85714286  6.          6.14285714  6.28571429
  6.42857143  6.57142857  6.71428571  6.85714286  7.          7.14285714
  7.28571429  7.42857143  7.57142857  7.71428571  7.85714286  8.
  8.14285714  8.28571429  8.42857143  8.57142857  8.71428571  8.85714286
  9.          9.14285714  9.28571429  9.42857143  9.57142857  9.71428571
  9.85714286 10.        ]


<b>4:</b>  Create the numpy array
```
a = [[ 1,  2,  3,  4],
     [ 5,  6,  7,  8],
     [ 9, 10, 11, 12],
     [13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
```

In [5]:
A = np.arange(1,25).reshape(6,4) #First create the 1-D vector [1 2 ... 23 24] and then reshape it to a 6 x 4 matrix
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


<b>5:</b>  From the numpy array created in the previous question, select all odd-numbered rows (indices 1, 3 and 5; note that the top row has index 0) and last two columns, i.e., the matrix
```
B = [[ 7,  8],
     [15, 16],
     [23, 24]].
```
Use slicing.

In [6]:
B = A[1::2,-2:] 
print(B)
#1::2 slicing: We select all rows starting from row 1 in steps of 2 (resulting in only the odd rows); 
#-2: slicing: We select only the last two rows. Recall that the index of the last row is -1, of the second to last row is -2, etc..

[[ 7  8]
 [15 16]
 [23 24]]


<b>6:</b>  Create the numpy array
```
[1, 5, 9, 2, 6, 10, 3, 7, 11, 4, 8, 12]
```
from the first three rows of `A` (see Exercise 4).

In [12]:
C = A[:3].T.flatten() 
print(C)
#We first select the first three rows of A with A[:3]. 
#Because of the 'largest index changes fastest' principle, flattening A[:3] would result in [ 1 2 3 ... 10 11 12].
#Therefore we first tranpose A[:3] to get the desired result.

[ 1  5  9  2  6 10  3  7 11  4  8 12]


<b>7:</b>  Create the numpy arrays
```
X = [[1, 2, 3],
     [4, 5, 6]]
Y = [[7, 8, 9],
     [10, 11, 12]]
```
and use them to create the arrays
```
W = [[ 1,  2,  3,  7,  8,  9],
     [ 4,  5,  6, 10, 11, 12]]
```
and
```
Z = [[ 1,  2,  3],
     [ 4,  5,  6],
     [ 7,  8,  9],
     [10, 11, 12]].
```

In [35]:
X = np.arange(1,7).reshape(2,3)
Y = np.arange(7,13).reshape(2,3)

W = np.hstack((X,Y))
Z = np.vstack((X,Y))
print('W = \n', W)
print('Z = \n', Z)

W = 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Z = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


<b>8:</b> Create a new array by appending only the second row of `Y` at the bottom of `X` (with `X` and `Y` as in Exercise 7).

In [36]:
Z = np.vstack((X,Y[1,:]))
print(Z)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]


<b>9:</b> Let x be the array ```[0, 1, 2]```. Convert it to the array `X` given by
```
[[0, 1, 2, 0, 1, 2]
 [0, 1, 2, 0, 1, 2]].
```

In [37]:
x = np.arange(0,3)
X = np.tile(x,(2,2))
print(X)

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


<b>10:</b> Let ```x = [0, 1, 2]```. Use it to create ```y = [0, 0, 1, 1, 2, 2]```.

In [39]:
y = np.repeat(x,2)
print(y)

[0 0 1 1 2 2]


<b>11:</b> Let X be array 
```
[[1, 2, 3], 
 [4, 5, 6]].
``` 
Convert it to `[1 4 2 5 3 6]`.

In [40]:
X = np.arange(1,7).reshape(2,3)
Y = X.T.flatten()
print(Y)
#This exercise is similar to Exercise 6

[1 4 2 5 3 6]


<b>12:</b> Write a function that for input numbers `a` and `b`, and non-negative input vector `x`, returns the vector `y` with $y[i] = a\cdot x[i] + b$ if $0 < x[i] < 10$ and $y[i] = 0$ otherwise.

In [46]:
def y(a,b,x):
    return np.where((0 < x) & (x < 10), a*x +b, 0)

#We use np.where() to first select all x[i] for which 0 < x[i] < 10. 
#We then set those indices equal to a*x + b and all the others equal to 0

<b>13:</b> Write a function that for given $n$ and $m$ returns an $(m+n) \times (m+n)$ matrix that contains an $m \times m$ block of ones on the top left, and an $n \times n$ block of ones on the bottom right (and zeros elsewhere). For $m = 2$ and $n = 3$, this results in the matrix
```
       [[1,  1,  0,  0,  0],
        [1,  1,  0,  0,  0],
        [0,  0,  1,  1,  1],
        [0,  0,  1,  1,  1],
        [0,  0,  1,  1,  1]].
```

In [54]:
def blocks(m,n):
    X1 = np.ones((m,m),dtype='int')
    X2 = np.ones((n,n),dtype='int')
    Y1 = np.zeros((m,n),dtype='int')
    Y2 = np.zeros((n,m),dtype='int')
    return np.vstack((np.hstack((X1,Y1)),np.hstack((Y2,X2))))

#Testing
print(blocks(2,3))

[[1 1 0 0 0]
 [1 1 0 0 0]
 [0 0 1 1 1]
 [0 0 1 1 1]
 [0 0 1 1 1]]


### Data processing

<b>14:</b> Import the data from the file `Exercises1_data.dat` (download it from https://pskleer2.github.io and store it in the same folder with the .py file containing your solutions) into an array called `x`.

In [57]:
x = np.loadtxt('Exercises1_data.dat')
print(x[0:5])

[[ 6.19362116e-01  2.53859624e-04 -5.77868842e-01 -5.46021320e-01
   1.01226554e+00 -7.94321795e-01 -1.34344431e+00 -5.20388262e-01
   2.06714383e+00  6.04037564e-01 -1.40515154e+00 -1.02149507e-01
  -6.84819553e-01  1.62899971e+00 -6.13753541e-01  1.28077713e+00
   6.39427976e-01 -1.13663577e+00  7.17286301e-01  1.31447085e+00]
 [ 7.90362766e-01 -1.49996118e+00 -8.90261233e-01  1.07570141e+00
   8.57925392e-01 -1.64150194e+00  1.46856162e+00  1.99645587e-02
  -1.33022418e-01 -1.40395836e+00  2.81845450e-01  2.23309368e-01
   3.27595814e-02  3.99622502e-01  1.10973655e+00  5.64855247e-01
  -4.85586027e-01  1.49128730e+00  7.97397948e-03 -3.33075765e-01]
 [ 8.15666933e-01  1.13718501e+00 -3.35037912e-01  7.48426462e-01
   2.27989069e-01  3.72473658e-01 -1.15054420e+00 -1.17743508e+00
   1.42215444e+00  1.00154270e+00  8.21727326e-01  4.29182458e-01
   1.38809493e-01 -7.97703141e-01 -8.66938547e-01 -3.66876897e-01
   1.41335592e+00  8.23943938e-01  2.80963059e-01  6.47260046e-01]
 [ 8.32

<b>15:</b> Find all column indices of `x` whose column sum is positive.

In [59]:
y = np.where(np.sum(x,axis=0) > 0)
print(y[0]) #np.where() returns two arguments

[ 3  5  9 10 12 13 16 19]


<b>16:</b> For each of the columns of `x` with positive column sum, return the maximum entry.

In [62]:
z = np.max(x[:,y[0]],axis=0)
print(z)

[2.11539965 2.9298793  2.83664452 2.21286061 2.9576122  2.28352649
 2.18420931 2.25536157]


### Writing some mathematical functions

<b>17:</b> Write a function that normalizes a 2D input array (matrix) such that all entries in a column are between 0 and 1 (smallest entry mapped to 0, largest value mapped to 1). Test your function on $A$ as given below. 

In [7]:
A = np.array([[ 1,  2,  3,  0],
       [ 5,  6,  -7,  0],
       [ -9, 10, 11, 0],
       [13, -13, 15, 0],
       [17, 18, 19, 0],
       [-21, -22, -23, 0]])

B =  np.array([[ 1,  2,  3,  0],
       [ 5,  6,  -7,  0],
       [ -9, 10, 11, 2],
       [13, -13, 15, 0],
       [17, 18, 19, 4],
       [-21, -22, -23, 0]])

In [11]:
def normalize(A):
    col_min = np.min(A,axis=0)
    col_max = np.max(A,axis=0)
    if (col_max - col_min == 0).any(): 
        return print('The matrix contains a column whose entries are all the same')
    else:
        return (A - col_min)/(col_max - col_min)

#(Original solution; the if-statement of this function is rather cumbersome...)
def normalize_old(A):
    col_min = np.min(A,axis=0)
    col_max = np.max(A,axis=0)
    if len(np.nonzero(col_max - col_min)[0]) != np.shape(A)[1]: #Other possibilities here as well.
        return print('The matrix contains a column whose entries are all the same')
    else:
        return (A - col_min)/(col_max - col_min)

In [12]:
#Testing
print('Normalized matrix A = \n',normalize(A))
print('Normalized matrix B = \n',normalize(B))

The matrix contains a column whose entries are all the same
Normalized matrix A = 
 None
Normalized matrix B = 
 [[0.57894737 0.6        0.61904762 0.        ]
 [0.68421053 0.7        0.38095238 0.        ]
 [0.31578947 0.8        0.80952381 0.5       ]
 [0.89473684 0.225      0.9047619  0.        ]
 [1.         1.         1.         1.        ]
 [0.         0.         0.         0.        ]]


<b>18:</b> Write a function that normalizes a 2D input array (matrix) such that the entries in each row have mean 0 and standard deviation 1. Test your function on the array A above. Also verify that the rows have mean 0 (using `np.mean()`) and standard deviation 1 (using `np.std()`) 

In [68]:
#Function
def normalize_mean_std(A):
    row_mean = np.mean(A,axis=1)
    row_std = np.std(A,axis=1)
    return (A - row_mean[:,None])/row_std[:,None]

#Testing
N = normalize_mean_std(A)
print(N)

#Checking mean condition
print(np.mean(N,axis=1))

#Checking std condition
print(np.std(N,axis=1))

[[-0.4472136   0.4472136   1.34164079 -1.34164079]
 [ 0.77702869  0.97128586 -1.55405738 -0.19425717]
 [-1.47153441  0.85839508  0.98102294 -0.3678836 ]
 [ 0.82181649 -1.48815418  0.99950654 -0.33316885]
 [ 0.4472136   0.57498891  0.70276422 -1.72496673]
 [-0.47108153 -0.57576631 -0.6804511   1.72729894]]
[ 0.00000000e+00 -6.93889390e-18  0.00000000e+00  2.77555756e-17
  0.00000000e+00  0.00000000e+00]
[1. 1. 1. 1. 1. 1.]


<b>19:</b> Write a function that extracts the anti-diagonal of the matrix
```
A = [[ 1,  2,  3],
     [ 5,  6,  -7],
     [ -9, 10, 11]]
```
this would be `[-9,6,3]`. <i>Hint: Use `np.rot90` to rotate a matrix $90$ degrees. Have a look at the <a href="https://numpy.org/doc/stable/reference/generated/numpy.rot90.html">documentation</a> for details of how this function works.</i>

In [69]:
A = np.array([
   [ 1,  2,  3],
   [ 5,  6,  -7],
   [ -9, 10, 11]])

In [74]:
d = np.diag(np.rot90(A,k=3,axes=(0,1))) #We first rotate the matrix 3*90 = 270 degrees and then take the diagonal.
print(d)

[-9  6  3]
